server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update #如果数据库的字段发生变化和实体类不一样,会实时更新
    show-sql: true
    thymeleaf:
      mode: HTML
      messages:
        basename: i18n/messages
logging:
  level:
    root: warn
    com.wey: info
  file: log/blog-pro.log
comment.avatar: /images/avatar.png
